/** Saemtliche UI-Texte zentral auf Deutsch. */

export const STR = {
  title: 'Neon Arena',
  subtitle: 'Überlebe die Wellen',

  // Menue
  play: 'Spielen',
  shop: 'Werkstatt',
  bestScore: 'Bestwert',
  difficulty: 'Schwierigkeit',
  autoAim: 'Auto-Zielen',
  weaponSelect: 'Waffe',
  on: 'An',
  off: 'Aus',
  locked: 'Gesperrt',
  hardLockedHint: 'Erreiche Welle 10 auf Normal',
  menuHint: 'Bewegen: WASD / Pfeile · Dash: Leertaste · Pause: P / Esc',
  saveWarning: 'Achtung: Fortschritt kann nicht gespeichert werden (Speicher blockiert).',
  dailySeed: 'Tages-Arena',
  dailySeedHint: 'Jeden Tag dieselben Wellen für alle',
  // NEU (Reise-Modus)
  journeyMode: 'Reise-Modus',
  journeyModeHint: 'Wähle nach jeder Welle deinen Weg',

  difficulties: {
    easy: 'Einfach',
    normal: 'Normal',
    hard: 'Schwer',
  } as Record<string, string>,

  // HUD
  wave: 'Welle',
  waveShort: 'W',
  enemiesLeft: 'Gegner übrig',
  combo: 'Combo',

  // Wellen-Banner
  waveCleared: 'Welle geschafft!',
  wavePerfect: 'Perfekt!',
  waveIncoming: 'Welle',
  bossIncoming: 'Boss!',
  hardUnlocked: 'Neuer Modus freigeschaltet: Schwer!',

  // Ueberraschungen
  goldenWave: '★ Goldene Welle! Doppelte Kerne! ★',
  capsuleIncoming: 'Versorgung im Anflug!',
  capsuleRewards: {
    cores: 'Kern-Regen!',
    hearts: 'Extra-Herzen!',
    magnet: 'Magnet!',
    rapidFire: 'Turbofeuer!',
  } as Record<string, string>,
  thiefEscaped: 'Dieb entkommen!',
  eliteSpawned: 'Elite!',

  // Upgrade-Screen
  chooseUpgrade: 'Wähle ein Upgrade!',
  reroll: 'Neu würfeln',
  rerollUsed: 'Verbraucht',
  stacksLabel: 'Stufe',
  rarities: {
    common: 'Gewöhnlich',
    rare: 'Selten',
    epic: 'Episch',
    legendary: 'Legendär',
    mythic: 'Mythisch', // NEU
  } as Record<string, string>,
  legendaryFound: 'LEGENDÄR!',
  mythicFound: 'MYTHISCH!', // NEU: Banner-Text beim Waehlen eines mythischen Upgrades

  // NEU (Reise-Modus): Weg-Wahl-Screen
  chooseRoom: 'Wähle deinen Weg!',
  chooseRoomCoop: 'Wählt euren Weg!',
  rooms: {
    normal: { name: 'Kampf', risk: 'Normale Welle', reward: 'Solider Kampf', flavor: 'Nur du und die Meute.' },
    treasure: { name: 'Schatzkammer', risk: 'Normale Gegner', reward: 'Garantiert Seltenes + Kerne', flavor: 'Gold glänzt in der Tiefe.' },
    elite: { name: 'Elite-Kammer', risk: 'Viele Elite-Gegner', reward: 'Reiche Beute + Seltenes', flavor: 'Die Starken warten.' },
    storm: { name: 'Sturm', risk: 'Schneller & stärker', reward: 'Doppelte Kerne', flavor: 'Der Himmel tobt.' },
    oasis: { name: 'Oase', risk: 'Wenige Gegner', reward: 'Heilung', flavor: 'Kurz durchatmen.' },
    mystery: { name: '???', risk: 'Unbekannt', reward: 'Überraschung', flavor: 'Was wartet dahinter?' },
    horde: { name: 'Schwarm', risk: 'Riesige Übermacht', reward: 'Combo-Fest + Kerne', flavor: 'Sie kommen zu Tausenden.' },
    finsternis: { name: 'Finsternis', risk: 'Kampf im Dunkeln', reward: 'Extra Kerne', flavor: 'Das Licht stirbt.' },
    singular: { name: 'Singularität', risk: 'Sog zur Mitte', reward: 'Reiche Beute + Seltenes', flavor: 'Alles zieht zur Mitte.' },
    minefield: { name: 'Minenfeld', risk: 'Boden-Explosionen', reward: 'Extra Kerne', flavor: 'Der Boden lauert.' },
    tanks: { name: 'Panzerwall', risk: 'Zähe Kolosse', reward: 'Extra Kerne', flavor: 'Die Kolosse rollen an.' },
    shooters: { name: 'Schützenstand', risk: 'Kugelhagel von fern', reward: 'Extra Kerne', flavor: 'Kugelhagel von fern.' },
    phantoms: { name: 'Geisterstunde', risk: 'Teleport-Chaos', reward: 'Extra Kerne', flavor: 'Überall und nirgends.' },
    splitters: { name: 'Zellteilung', risk: 'Endlose Teilung', reward: 'Combo-Fest + Kerne', flavor: 'Teile und zerteile.' },
    windkanal: { name: 'Windkanal', risk: 'Ständiger Sog zur Seite', reward: 'Extra Kerne', flavor: 'Stell dich gegen den Wind.' },
    glasscannon: { name: 'Glaskanonen', risk: 'Zerbrechlich, aber hart', reward: 'Extra Kerne', flavor: 'Ein Treffer entscheidet.' },
    collapse: { name: 'Kollaps-Arena', risk: 'Die Wände schließen sich', reward: 'Extra Kerne', flavor: 'Die Wände kommen näher.' },
  } as Record<string, { name: string; risk: string; reward: string; flavor: string }>,

  // Pause
  pause: 'Pause',
  resume: 'Weiter',
  restart: 'Neustart',
  options: 'Optionen',
  mainMenu: 'Hauptmenü',
  volumeMaster: 'Lautstärke',
  volumeSfx: 'Effekte',
  volumeMusic: 'Musik',
  reduceFx: 'Effekte reduzieren',
  damageNumbers: 'Schadenszahlen',
  vibration: 'Vibration',

  // Gamepad
  padDisconnected: 'Gamepad getrennt — Pause!',
  padHint: '🎮 Stick: Laufen · A: Dash · LT: Spezial · Start: Pause',
  padNavHint: '🎮 Steuerkreuz: Auswählen · A: Bestätigen · B: Zurück',
  padSoundHint: '🔇 Einmal klicken oder Taste drücken, dann gibt es Sound — das Gamepad ist schon bereit!',

  // Koop
  coopButton: '🤝 Zusammen',
  coopSetupTitle: 'Wer spielt mit?',
  coopP1Label: 'Spieler 1',
  coopP2Label: 'Spieler 2',
  guest: 'Gast',
  guestHint: 'Speichert nichts',
  coopStart: 'Los geht’s!',
  coopJoinHint: 'Spieler 2: Enter drücken zum Beitreten! (Gamepad: A-Taste)',
  coopSourcePad: (n: number) => `🎮 Gamepad ${n}`,
  coopSourceArrows: '⌨ Pfeiltasten + Enter',
  coopSourceWasd: '⌨ WASD + Leertaste',
  coopSourceNone: 'Noch nicht beigetreten',
  coopNeedsJoin: 'Spieler 2 muss erst beitreten!',
  upgradeChooser: (name: string) => `${name} wählt`,
  hudDown: 'AM BODEN',
  downedBanner: (name: string) => `${name} ist am Boden! Lauf hin und hilf!`,
  coopRevivedBanner: 'Gerettet!',
  lbCoop: 'Koop',

  // Game Over
  gameOverTitle: 'Runde vorbei!',
  newRecord: 'Neuer Bestwert!',
  reachedWave: 'Erreichte Welle',
  coresEarned: 'Kerne verdient',
  again: 'Nochmal!',
  toMenu: 'Menü',
  nextUnlockTeaser: (name: string, missing: number) => `Nur noch ${missing} Kerne bis: ${name}`,
  shopAffordable: 'Du kannst etwas Neues in der Werkstatt freischalten! 🛠',
  restartHint: 'Taste R für sofortigen Neustart',
  runSummary: {
    build: 'Dein Build',
    dps: 'Schaden/s',
    strongestHit: 'Stärkster Treffer',
    bestCombo: 'Beste Combo',
  },

  // Profile & Bestenliste
  profilesTitle: 'Wer spielt?',
  profileSwitch: 'Spieler',
  newProfileTitle: 'Neuer Spieler',
  newProfilePlaceholder: 'Name eingeben',
  createProfile: 'Anlegen',
  deleteProfile: 'Löschen',
  deleteConfirm: 'Wirklich löschen?',
  activeBadge: 'Aktiv',
  profilesFull: 'Maximal 8 Spieler',
  leaderboard: 'Bestenliste',
  leaderboardTitle: 'Bestenliste',
  leaderboardEmptyHint: 'Spielt eine Runde, um hier zu erscheinen!',
  lbName: 'Spieler',
  lbBestWave: 'Beste Welle',
  lbModeClassic: '⚔️ Klassik',
  lbModeJourney: '🧭 Reise',

  // Erfolge (intern weiter "album"/"sticker" — nur sichtbarer Text umbenannt)
  album: 'Erfolge',
  albumTitle: 'Deine Erfolge',
  albumTotal: (got: number, total: number) => `${got} von ${total} Erfolgen`,
  albumNew: 'NEU!',
  albumSecretName: '???',
  albumClaim: 'Abholen!',
  albumClaimed: 'Abgeholt',
  albumRewardLocked: 'Sammle alle Erfolge dieser Seite!',
  albumRewardCores: (n: number) => `Belohnung: ⬡ ${n} Kerne`,
  albumRewardColorway: (name: string) => `Belohnung: Farbe „${name}"`,
  albumRewardTrail: (name: string) => `Belohnung: Spur „${name}"`,
  albumGoldReward: (n: number) => `Alle ${n} Erfolge: GOLD-Farbe für alle Helden!`,
  albumSince: (date: string) => `Seit ${date}`,
  albumProgress: (got: number, total: number) => `${got}/${total}`,
  newSticker: 'Neuer Erfolg!',
  gameOverNewStickers: 'Neue Erfolge:',
  colorLabel: 'Farbe',
  colorDefault: 'Standard',
  // NEU (Belohnungsart): Spur-Effekte
  trailLabel: 'Spur',
  trailNone: 'Keine',
  trails: {
    komet: 'Komet',
    funken: 'Funken',
    plasma: 'Plasma',
    frost: 'Frost',
    regenbogen: 'Regenbogen',
  } as Record<string, string>,

  albumPages: {
    start: 'Erste Schritte',
    kampf: 'Kampfkunst',
    bosse: 'Boss-Jäger',
    sammler: 'Sammler',
    meister: 'Meisterschaft',
    team: 'Team-Werk',
    geheim: 'Geheimnisse',
    ausdauer: 'Ausdauer',
    herausforderung: 'Herausforderung',
    geheim2: 'Geheimnisse II',
    reise: 'Reise',
    reise2: 'Reise-Meister',
    reiseGeheim: 'Geheime Reise',
  } as Record<string, string>,

  colorways: {
    limette: 'Limette',
    aurora: 'Aurora',
    bonbon: 'Bonbon',
    ultraviolett: 'Ultraviolett',
    sonnenglut: 'Sonnenglut',
    tiefsee: 'Tiefsee',
    gold: 'Gold',
    eisblau: 'Eisblau',
    smaragd: 'Smaragd',
    kobalt: 'Kobalt',
    platin: 'Platin',
    prismatisch: 'Prismatisch',
    amethyst: 'Amethyst',
    kosmos: 'Kosmos',
    sternenstaub: 'Sternenstaub',
  } as Record<string, string>,

  stickers: {
    ersterFunke: { name: 'Erster Funke', desc: 'Besiege deinen ersten Gegner' },
    wellenreiter: { name: 'Wellenreiter', desc: 'Schaffe deine erste Welle' },
    wusch: { name: 'Wusch!', desc: 'Mache deinen ersten Dash' },
    herzenssache: { name: 'Herzenssache', desc: 'Sammle ein Herz ein' },
    magnetisch: { name: 'Magnetisch', desc: 'Sammle einen Magneten ein' },
    aufgeruestet: { name: 'Aufgerüstet', desc: 'Wähle dein erstes Upgrade' },
    kernSammler: { name: 'Kern-Sammler', desc: 'Sammle insgesamt 100 Kerne' },
    bossInSicht: { name: 'Boss in Sicht', desc: 'Triff auf deinen ersten Boss' },
    blitzblank: { name: 'Blitzblank', desc: 'Schaffe eine Welle ohne Treffer' },
    stammgast: { name: 'Stammgast', desc: 'Spiele 10 Runden' },

    comboKueken: { name: 'Combo-Küken', desc: 'Erreiche Combo ×1,5' },
    comboProfi: { name: 'Combo-Profi', desc: 'Erreiche Combo ×2' },
    comboMeister: { name: 'Combo-Meister', desc: 'Erreiche Combo ×3' },
    scharfschuetze: { name: 'Scharfschütze', desc: 'Lande insgesamt 100 Volltreffer' },
    panzerknacker: { name: 'Panzerknacker', desc: 'Besiege insgesamt 10 Panzer' },
    geisterjaeger: { name: 'Geisterjäger', desc: 'Besiege insgesamt 15 Phantome' },
    eliteSchreck: { name: 'Elite-Schreck', desc: 'Besiege insgesamt 10 Eliten' },
    unberuehrbar: { name: 'Unberührbar', desc: '3 perfekte Wellen in einer Runde' },

    prismaZerlegt: { name: 'Prisma zerlegt', desc: 'Besiege PRISMA' },
    goliathGestuerzt: { name: 'Goliath gestürzt', desc: 'Besiege GOLIATH' },
    minosEntschaerft: { name: 'Minos entschärft', desc: 'Besiege MINOS' },
    hydraGestutzt: { name: 'Hydra gestutzt', desc: 'Besiege den HYDRA-KERN' },
    wirbelGestoppt: { name: 'Wirbel gestoppt', desc: 'Besiege WIRBEL' },
    bossSammlung: { name: 'Boss-Sammlung', desc: 'Besiege alle 5 Bosse' },
    makelloserBoss: { name: 'Makelloser Bosskampf', desc: 'Besiege einen Boss, ohne getroffen zu werden' },
    ueberBoss: { name: 'Über-Boss', desc: 'Besiege einen „+"-Boss (ab Welle 30)' },

    kernschatz: { name: 'Kern-Schatz', desc: 'Sammle insgesamt 500 Kerne' },
    kernDrache: { name: 'Kern-Drache', desc: 'Sammle insgesamt 5.000 Kerne' },
    goldrausch: { name: 'Goldrausch', desc: 'Erlebe eine Goldene Welle' },
    paeckchen: { name: 'Päckchen!', desc: 'Öffne eine Versorgungskapsel' },
    paketProfi: { name: 'Paket-Profi', desc: 'Erhalte alle 4 Kapsel-Belohnungen' },
    tagesheld: { name: 'Tagesheld', desc: 'Beende eine Tages-Arena-Runde' },
    heldenTrio: { name: 'Helden-Trio', desc: 'Beende eine Runde mit jedem Helden' },
    waffenkammer: { name: 'Waffenkammer', desc: 'Beende eine Runde mit jeder Waffe' },
    legendenAlbum: { name: 'Legenden-Album', desc: 'Wähle jedes legendäre Upgrade einmal' },

    welle10: { name: 'Welle 10', desc: 'Erreiche Welle 10' },
    welle15: { name: 'Welle 15', desc: 'Erreiche Welle 15' },
    welle20: { name: 'Welle 20', desc: 'Erreiche Welle 20' },
    harteSchale: { name: 'Harte Schale', desc: 'Erreiche Welle 10 auf Schwer' },
    punkteSturm: { name: 'Punkte-Sturm', desc: '25.000 Punkte in einer Runde' },
    schlaechter1: { name: 'Schlächter I', desc: 'Besiege insgesamt 1.000 Gegner' },
    schlaechter2: { name: 'Schlächter II', desc: 'Besiege insgesamt 5.000 Gegner' },
    schlaechter3: { name: 'Schlächter III', desc: 'Besiege insgesamt 20.000 Gegner' },
    perfektionist: { name: 'Perfektionist', desc: '100 perfekte Wellen insgesamt' },

    doppeltHaelt: { name: 'Doppelt hält besser', desc: 'Beende eine Runde zu zweit' },
    retterInDerNot: { name: 'Retter in der Not', desc: 'Belebe deinen Partner wieder' },
    teamWelle10: { name: 'Team-Welle 10', desc: 'Erreicht zu zweit Welle 10' },
    niemandFaellt: { name: 'Niemand fällt', desc: 'Besiegt einen Boss, ohne dass jemand zu Boden geht' },

    aufFrischerTat: { name: 'Auf frischer Tat', desc: 'Erwische den Dieb, bevor er etwas klaut', hint: 'Schnapp den Langfinger, bevor er zulangt …' },
    spaghettiMonster: { name: 'Spaghetti-Monster', desc: '3 Gegner mit einem Schwarzen Loch verschlingen', hint: 'Füttere die Dunkelheit richtig satt …' },
    standhaft: { name: 'Standhaft', desc: 'Besiege einen Boss ohne einen einzigen Dash', hint: 'Wer nicht springt, gewinnt trotzdem …' },
    umHaaresbreite: { name: 'Um Haaresbreite', desc: 'Beende eine Welle mit höchstens 5 Leben', hint: 'Puh, das war knapp …' },
    wiederDa: { name: 'Wieder da!', desc: 'Nutze die Zweite Chance', hint: 'Es gibt einen Weg zurück … (Psst: Werkstatt!)' },
    goldenePerfektion: { name: 'Goldene Perfektion', desc: 'Schaffe eine Goldene Welle ohne Treffer', hint: 'Wenn alles golden glänzt, bleib makellos …' },

    welle25: { name: 'Welle 25', desc: 'Erreiche Welle 25' },
    welle30: { name: 'Welle 30', desc: 'Erreiche Welle 30' },
    welle35: { name: 'Welle 35', desc: 'Erreiche Welle 35' },
    welle40: { name: 'Welle 40', desc: 'Erreiche Welle 40 — bringt 300 Kerne' },
    welle50: { name: 'Welle 50', desc: 'Erreiche Welle 50 — schaltet die Farbe „Platin" frei' },
    kernMagnat: { name: 'Kern-Magnat', desc: 'Sammle insgesamt 25.000 Kerne' },
    dauerlaeufer: { name: 'Dauerläufer', desc: 'Schaffe insgesamt 300 Wellen' },
    marathon: { name: 'Marathon', desc: 'Schaffe insgesamt 1.000 Wellen — bringt 300 Kerne' },
    veteran: { name: 'Veteran', desc: 'Spiele 50 Runden' },
    altgedienter: { name: 'Altgedienter', desc: 'Spiele 200 Runden' },
    schlaechter4: { name: 'Schlächter IV', desc: 'Besiege insgesamt 50.000 Gegner — bringt 500 Kerne' },

    makelloserKrieger: { name: 'Makelloser Krieger', desc: 'Besiege einen Boss ohne Treffer UND ohne einen Dash' },
    eisenwille: { name: 'Eiserner Wille', desc: 'Erreiche Welle 15, ohne in der ganzen Runde zu dashen' },
    unantastbar: { name: 'Unantastbar', desc: 'Erreiche Welle 10, ohne ein einziges Mal getroffen zu werden — bringt 500 Kerne' },
    hochBoss: { name: 'Gipfelstürmer', desc: 'Besiege einen Boss auf Welle 40 oder höher' },
    fuenfPerfekt: { name: 'Fünf Makellose', desc: 'Schaffe 5 perfekte Wellen in einer Runde' },
    comboKoenig: { name: 'Combo-König', desc: 'Erreiche Combo ×4' },
    comboGott: { name: 'Combo-Gott', desc: 'Erreiche Combo ×5' },
    punkteGott: { name: 'Punkte-Gott', desc: '100.000 Punkte in einer Runde' },
    hartGesotten: { name: 'Hartgesotten', desc: 'Erreiche Welle 20 auf Schwer' },
    titan: { name: 'Titanentöter', desc: 'Besiege insgesamt 100 Panzer' },
    bezwinger: { name: 'Bezwinger', desc: 'Besiege jeden der 5 Bosse mindestens einmal ohne Treffer — schaltet die Regenbogen-Farbe „Prismatisch" frei' },

    paketMeister: { name: 'Paket-Meister', desc: 'Erhalte alle 4 Kapsel-Belohnungen in EINER Runde', hint: 'Sammle in einem Lauf jede Sorte Geschenk …' },
    langfingerJagd: { name: 'Langfinger-Jagd', desc: 'Erwische 10 Diebe, bevor sie klauen', hint: 'Mach Jagd auf die flinken Finger …' },
    schattentaenzer: { name: 'Schattentänzer', desc: 'Besiege einen Boss auf Welle 30+ ohne einen Dash', hint: 'Bleib ruhig stehen, auch wenn es spät wird …' },
    phoenix: { name: 'Phönix', desc: 'Belebe deinen Partner 3-mal in einer Runde wieder', hint: 'Zu zweit gibt niemand auf …' },
    nadeloehr: { name: 'Nadelöhr', desc: 'Beende eine Welle mit höchstens 3 Leben', hint: 'Noch knapper geht kaum …' },
    lochfuerst: { name: 'Loch-Fürst', desc: '5 Gegner mit einem einzigen Schwarzen Loch verschlingen', hint: 'Füttere die Dunkelheit bis zum Rand …' },
    eiserneReserve: { name: 'Eiserne Reserve', desc: 'Erreiche Welle 10, ohne ein Herz zu sammeln', hint: 'Wer clever ausweicht, braucht keine Heilung …' },
    genuegsam: { name: 'Genügsam', desc: 'Erreiche Welle 10, ohne einen Kern aufzusammeln', hint: 'Lass allen Glanz einfach liegen …' },

    ersteReise: { name: 'Erste Reise', desc: 'Spiele eine Runde im Reise-Modus' },
    schatzjaeger: { name: 'Schatzjäger', desc: 'Räume 5 Schatzkammern im Reise-Modus' },
    sturmreiter: { name: 'Sturmreiter', desc: 'Räume 5 Sturm-Räume im Reise-Modus' },
    finsterWanderer: { name: 'Finster-Wanderer', desc: 'Räume 3 Finsternis-Räume im Reise-Modus' },
    eliteKammerHeld: { name: 'Elite-Kammer-Held', desc: 'Räume 5 Elite-Kammern im Reise-Modus' },
    reiseWelle15: { name: 'Weit gereist', desc: 'Erreiche Welle 15 im Reise-Modus' },
    mutprobe: { name: 'Mutprobe', desc: 'Räume insgesamt 25 Risiko-Räume im Reise-Modus' },
    reiseProfi: { name: 'Reise-Profi', desc: 'Spiele 15 Runden im Reise-Modus' },
    weltenbummler: { name: 'Weltenbummler', desc: 'Besuche jeden Raum-Typ im Reise-Modus mindestens einmal' },
    reiseWelle25: { name: 'Ferne Welten', desc: 'Erreiche Welle 25 im Reise-Modus — bringt 400 Kerne' },

    minenmeister: { name: 'Minenmeister', desc: 'Räume 5-mal ein Minenfeld' },
    panzerbrecher: { name: 'Panzerbrecher', desc: 'Räume 5-mal einen Panzerwall' },
    kugelhagel: { name: 'Kugelhagel', desc: 'Räume 5-mal einen Schützenstand' },
    geisterbanner: { name: 'Geisterbanner', desc: 'Räume 5-mal eine Geisterstunde' },
    windlaeufer: { name: 'Windläufer', desc: 'Räume 5-mal einen Windkanal' },
    glasbrecher: { name: 'Glasbrecher', desc: 'Räume 5-mal einen Glaskanonen-Raum' },
    wandbrecher: { name: 'Wandbrecher', desc: 'Räume 5-mal eine Kollaps-Arena' },
    wagemut: { name: 'Wagemut', desc: 'Räume 60 Risiko-Räume im Reise-Modus — bringt die Spur „Komet"' },
    reiseVeteran: { name: 'Reise-Veteran', desc: 'Spiele 30 Reise-Läufe — bringt die Spur „Plasma"' },
    reiseWelle30: { name: 'Grenzgänger', desc: 'Erreiche Welle 30 im Reise-Modus — bringt die Spur „Funken"' },
    neulandErkunder: { name: 'Neuland-Erkunder', desc: 'Meistere jeden neuen Reise-Raum — bringt die Spur „Frost"' },
    reiseKenner: { name: 'Reise-Kenner', desc: 'Räume 150 Risiko-Räume im Reise-Modus — bringt 500 Kerne' },

    reiseUnberuehrt: { name: 'Unberührt', desc: 'Erreiche Welle 25 im Reise-Modus ohne einen Treffer — bringt die Spur „Regenbogen"', hint: 'Weit reisen, ohne einen Kratzer …' },
    reiseDaemon: { name: 'Dämon der Reise', desc: 'Erreiche Welle 30 im Reise-Modus ohne einen Treffer — bringt 1000 Kerne', hint: 'Makellos, bis tief in die Nacht …' },
    reiseGrenzenlos: { name: 'Grenzenlos', desc: 'Erreiche Welle 40 im Reise-Modus — bringt 700 Kerne', hint: 'Wie weit trägt dich der Weg wirklich?' },
    reiseEisern: { name: 'Eiserne Reise', desc: 'Erreiche Welle 20 im Reise-Modus ohne einen Dash', hint: 'Bleib am Boden, egal wie lang der Weg …' },
    reiseAskese: { name: 'Askese', desc: 'Erreiche Welle 20 im Reise-Modus ohne ein Herz zu sammeln', hint: 'Reise weit und heile nie …' },
    reiseGenuegsam: { name: 'Reise-Genügsam', desc: 'Erreiche Welle 15 im Reise-Modus ohne einen Kern aufzusammeln', hint: 'Lass unterwegs allen Glanz liegen …' },
    reiseVielfalt: { name: 'Vielreisender', desc: 'Räume 8 verschiedene Raum-Typen in EINEM Reise-Lauf', hint: 'Nimm in einem Lauf jeden Weg mit …' },
  } as Record<string, { name: string; desc: string; hint?: string }>,

  // Shop
  shopTitle: 'Werkstatt',
  heroesSection: 'Helden',
  boniSection: 'Dauerhafte Boni',
  weaponsSection: 'Startwaffen',
  buy: 'Kaufen',
  bought: 'Gekauft',
  selected: 'Ausgewählt',
  select: 'Auswählen',
  maxed: 'Maximum',
  back: 'Zurück',
  cores: 'Kerne',

  // Helden
  heroes: {
    volt: { name: 'VOLT', trait: 'Der Allrounder – ausgewogen und zuverlässig' },
    blitz: { name: 'BLITZ', trait: 'Schnell und wendig, aber zerbrechlich' },
    brocken: { name: 'BROCKEN', trait: 'Zäher Koloss mit Streuschuss' },
    // NEU (Premium-Helden)
    koloss: { name: 'KOLOSS', trait: 'Wandelnde Festung – fast unverwüstlich, aber langsam' },
    kristall: { name: 'KRISTALL', trait: 'Schwebender Edelstein – elegant und ausgewogen' },
    phantom: { name: 'PHANTOM', trait: 'Hauchzarte Klinge – ein Treffer schmerzt, dein Schuss auch' },
    orbit: { name: 'ORBIT', trait: 'Kern im rotierenden Halo – das Meisterstück' },
  } as Record<string, { name: string; trait: string }>,

  // Held-Spezialfähigkeiten (Taste E / Pad LT)
  abilities: {
    volt: { name: 'Novaschlag', desc: 'Entlädt eine Schockwelle, die nahe Gegner wegfegt' },
    blitz: { name: 'Phasenblitz', desc: 'Blitzt unverwundbar ein großes Stück nach vorn' },
    brocken: { name: 'Schockstoß', desc: 'Wuchtige Druckwelle mit Rückstoß + kurze Unverwundbarkeit' },
    koloss: { name: 'Bollwerk', desc: 'Wird lange unverwundbar und friert Gegner ringsum ein' },
    kristall: { name: 'Prismasplitter', desc: 'Schleudert Kristallsplitter in alle Richtungen' },
    phantom: { name: 'Orbital-Schlag', desc: 'Ruft mehrere schwere Einschläge auf die zähesten Ziele' },
    orbit: { name: 'Singularität', desc: 'Wirft ein Schwarzes Loch, das Gegner bündelt und kollabiert' },
  } as Record<string, { name: string; desc: string }>,

  // Waffen
  weapons: {
    blaster: { name: 'Neon-Blaster', desc: 'Der treue Standard' },
    pulse: { name: 'Impulskanone', desc: 'Schnellfeuer, wenig Wumms' },
    spread: { name: 'Streuschuss', desc: '3 Kugeln im Fächer' },
    laser: { name: 'Laser-Lanze', desc: 'Durchbohrt ALLES in einer Linie' },
    star: { name: 'Sternenwerfer', desc: 'Bumerang-Stern, trifft doppelt' },
    // NEU (Premium-Helden-Startwaffen)
    moerser: { name: 'Wuchtmörser', desc: 'Langsam, schwer, mit Rückstoß' },
    railgun: { name: 'Railgun', desc: 'Ein brutaler Schuss, der alles durchbohrt' },
    prisma: { name: 'Prismaklinge', desc: 'Schneidender Kristallbolzen' },
    orbiter: { name: 'Orbiter', desc: 'Präziser, sauberer Schuss' },
  } as Record<string, { name: string; desc: string }>,

  // Bosse
  bosses: {
    prisma: 'PRISMA',
    goliath: 'GOLIATH',
    minos: 'MINOS',
    hydra: 'HYDRA-KERN',
    vortex: 'WIRBEL',
  } as Record<string, string>,
  bossTierSuffix: '+',

  // Upgrades
  upgrades: {
    fireRate: { name: 'Feuerrate', desc: '+12 % schneller schießen' },
    damage: { name: 'Schaden', desc: '+15 % Schaden' },
    speed: { name: 'Tempo', desc: '+8 % Lauftempo' },
    maxHp: { name: 'Panzerglas', desc: '+20 Leben, die Hälfte sofort geheilt' },
    magnet: { name: 'Magnet', desc: 'Sammelt Kerne von viel weiter weg' },
    range: { name: 'Fernblick', desc: '+20 % Reichweite und Schussgeschwindigkeit' },
    coreGreed: { name: 'Kern-Gier', desc: '+25 % Chance auf Kern-Drops' },
    multishot: { name: 'Mehrfachschuss', desc: '+1 Projektil (etwas weniger Schaden je Kugel)' },
    pierce: { name: 'Durchschlag', desc: 'Kugeln durchbohren +1 Gegner' },
    crit: { name: 'Volltreffer', desc: '+10 % Chance auf doppelten Schaden' },
    lifesteal: { name: 'Lebensraub', desc: '+1 Leben pro 2 Abschüsse' },
    orb: { name: 'Schutz-Orb', desc: 'Kreisender Orb schadet Gegnern' },
    dashBlade: { name: 'Dash-Klinge', desc: 'Dash verletzt durchquerte Gegner' },
    frost: { name: 'Frost-Schuss', desc: 'Treffer verlangsamen Gegner' },
    nova: { name: 'Nova-Kill', desc: '20 % Chance: Explosion bei Abschuss' },
    doubleDash: { name: 'Doppel-Dash', desc: 'Eine zweite Dash-Ladung' },
    ricochet: { name: 'Abpraller', desc: 'Kugeln springen zum nächsten Gegner' },
    mirrorClone: { name: 'Spiegelklon', desc: 'Ein Geisterklon feuert jeden Schuss mit!' },
    chainReaction: { name: 'Kettenreaktion', desc: 'JEDER besiegte Gegner explodiert!' },
    orbitalLaser: { name: 'Orbital-Laser', desc: 'Alle 5 Sekunden: Laser auf den stärksten Gegner' },
    blackHoleDash: { name: 'Schwarzes Loch', desc: 'Dash schleudert ein Schwarzes Loch, das Gegner ansaugt. Dann: Wumms!' },
    overcharge: { name: 'Überladung', desc: 'Unter 30 % Leben: +50 % Schaden' },
    megaShots: { name: 'Mega-Kugeln', desc: 'Riesige Kugeln: mehr Schaden, durchbohren Gegner' },
    // NEU: Mythische Upgrades (ueber legendaer, extrem selten)
    timeBreak: { name: 'Zeitbruch', desc: 'Alle Gegner UND ihre Schüsse stark verlangsamt!' },
    phoenixCore: { name: 'Phönixkern', desc: 'Einmal pro Lauf: Wiederauferstehung mit voller Energie und Schockwelle!' },
    prismBeam: { name: 'Prisma-Strahl', desc: 'Feuert unaufhörlich dicke, durchschlagende Regenbogen-Kugeln!' },
    singularity: { name: 'Singularität', desc: 'Feuerrate UND Schaden verdoppelt!' },
    corePack: { name: 'Kern-Paket', desc: 'Sofort +15 Kerne' },
    repair: { name: 'Reparatur', desc: 'Heilt sofort 25 % Leben' },
    scoreBoost: { name: 'Punkte-Schub', desc: 'Sofort Bonuspunkte (500 × Welle)' },
  } as Record<string, { name: string; desc: string }>,

  // Dauerhafte Boni
  permaBoni: {
    armor: { name: 'Panzerung', desc: '+10 % Start-Leben je Stufe' },
    calibration: { name: 'Kalibrierung', desc: '+6 % Schaden je Stufe' },
    turbo: { name: 'Turbo', desc: '+5 % Tempo je Stufe' },
    luck: { name: 'Glückskern', desc: '+10 % Kern-Chance je Stufe' },
    headstart: { name: 'Kopfstart', desc: 'Starte jede Runde mit 1 Gratis-Upgrade' },
    secondChance: { name: 'Zweite Chance', desc: '1× pro Runde: Wiederbelebung mit 50 % Leben' },
  } as Record<string, { name: string; desc: string }>,

  // Onboarding
  promptMove: 'Laufen!',
  promptShoot: 'Schießen!',
  promptDash: 'Dash!',
  promptAbility: 'Spezial einsetzen!',
  promptCollect: 'Kerne einsammeln!',

  // Sonstiges
  clickToStart: 'Klicke, um zu starten',
  revived: 'Zweite Chance!',
  phoenixRevived: '🔥 PHÖNIX! 🔥', // NEU (mythisch "Phoenixkern"): Auferstehungs-Banner
} as const;
