/** Saemtliche UI-Texte zentral auf Deutsch. */

export const STR = {
  title: 'Neon Arena',
  subtitle: 'Überlebe die Wellen',

  // Menue
  play: 'Spielen',
  shop: 'Werkstatt',
  bestScore: 'Bestwert',
  difficulty: 'Schwierigkeit',
  autoAim: 'Auto-Zielen',
  weaponSelect: 'Waffe',
  on: 'An',
  off: 'Aus',
  locked: 'Gesperrt',
  hardLockedHint: 'Erreiche Welle 10 auf Normal',
  menuHint: 'Bewegen: WASD / Pfeile · Dash: Leertaste · Pause: P / Esc',
  saveWarning: 'Achtung: Fortschritt kann nicht gespeichert werden (Speicher blockiert).',
  dailySeed: 'Tages-Arena',
  dailySeedHint: 'Jeden Tag dieselben Wellen für alle',

  difficulties: {
    easy: 'Einfach',
    normal: 'Normal',
    hard: 'Schwer',
  } as Record<string, string>,

  // HUD
  wave: 'Welle',
  waveShort: 'W',
  enemiesLeft: 'Gegner übrig',
  combo: 'Combo',

  // Wellen-Banner
  waveCleared: 'Welle geschafft!',
  wavePerfect: 'Perfekt!',
  waveIncoming: 'Welle',
  bossIncoming: 'Boss!',
  hardUnlocked: 'Neuer Modus freigeschaltet: Schwer!',

  // Ueberraschungen
  goldenWave: '★ Goldene Welle! Doppelte Kerne! ★',
  capsuleIncoming: 'Versorgung im Anflug!',
  capsuleRewards: {
    cores: 'Kern-Regen!',
    hearts: 'Extra-Herzen!',
    magnet: 'Magnet!',
    rapidFire: 'Turbofeuer!',
  } as Record<string, string>,
  thiefEscaped: 'Dieb entkommen!',
  eliteSpawned: 'Elite!',

  // Upgrade-Screen
  chooseUpgrade: 'Wähle ein Upgrade!',
  reroll: 'Neu würfeln',
  rerollUsed: 'Verbraucht',
  stacksLabel: 'Stufe',
  rarities: {
    common: 'Gewöhnlich',
    rare: 'Selten',
    epic: 'Episch',
    legendary: 'Legendär',
    mythic: 'Mythisch', // NEU
  } as Record<string, string>,
  legendaryFound: 'LEGENDÄR!',
  mythicFound: 'MYTHISCH!', // NEU: Banner-Text beim Waehlen eines mythischen Upgrades

  // Pause
  pause: 'Pause',
  resume: 'Weiter',
  restart: 'Neustart',
  options: 'Optionen',
  mainMenu: 'Hauptmenü',
  volumeMaster: 'Lautstärke',
  volumeSfx: 'Effekte',
  volumeMusic: 'Musik',
  reduceFx: 'Effekte reduzieren',
  damageNumbers: 'Schadenszahlen',
  vibration: 'Vibration',

  // Gamepad
  padDisconnected: 'Gamepad getrennt — Pause!',
  padHint: '🎮 Stick: Laufen · A: Dash · Start: Pause',
  padNavHint: '🎮 Steuerkreuz: Auswählen · A: Bestätigen · B: Zurück',
  padSoundHint: '🔇 Einmal klicken oder Taste drücken, dann gibt es Sound — das Gamepad ist schon bereit!',

  // Koop
  coopButton: '🤝 Zusammen',
  coopSetupTitle: 'Wer spielt mit?',
  coopP1Label: 'Spieler 1',
  coopP2Label: 'Spieler 2',
  guest: 'Gast',
  guestHint: 'Speichert nichts',
  coopStart: 'Los geht’s!',
  coopJoinHint: 'Spieler 2: Enter drücken zum Beitreten! (Gamepad: A-Taste)',
  coopSourcePad: (n: number) => `🎮 Gamepad ${n}`,
  coopSourceArrows: '⌨ Pfeiltasten + Enter',
  coopSourceWasd: '⌨ WASD + Leertaste',
  coopSourceNone: 'Noch nicht beigetreten',
  coopNeedsJoin: 'Spieler 2 muss erst beitreten!',
  upgradeChooser: (name: string) => `${name} wählt`,
  hudDown: 'AM BODEN',
  downedBanner: (name: string) => `${name} ist am Boden! Lauf hin und hilf!`,
  coopRevivedBanner: 'Gerettet!',
  lbCoop: 'Koop',

  // Game Over
  gameOverTitle: 'Runde vorbei!',
  newRecord: 'Neuer Bestwert!',
  reachedWave: 'Erreichte Welle',
  coresEarned: 'Kerne verdient',
  again: 'Nochmal!',
  toMenu: 'Menü',
  nextUnlockTeaser: (name: string, missing: number) => `Nur noch ${missing} Kerne bis: ${name}`,
  shopAffordable: 'Du kannst etwas Neues in der Werkstatt freischalten! 🛠',
  restartHint: 'Taste R für sofortigen Neustart',
  runSummary: {
    build: 'Dein Build',
    dps: 'Schaden/s',
    strongestHit: 'Stärkster Treffer',
    bestCombo: 'Beste Combo',
  },

  // Profile & Bestenliste
  profilesTitle: 'Wer spielt?',
  profileSwitch: 'Spieler',
  newProfileTitle: 'Neuer Spieler',
  newProfilePlaceholder: 'Name eingeben',
  createProfile: 'Anlegen',
  deleteProfile: 'Löschen',
  deleteConfirm: 'Wirklich löschen?',
  activeBadge: 'Aktiv',
  profilesFull: 'Maximal 8 Spieler',
  leaderboard: 'Bestenliste',
  leaderboardTitle: 'Bestenliste',
  leaderboardEmptyHint: 'Spielt eine Runde, um hier zu erscheinen!',
  lbName: 'Spieler',
  lbBestWave: 'Beste Welle',

  // Erfolge (intern weiter "album"/"sticker" — nur sichtbarer Text umbenannt)
  album: 'Erfolge',
  albumTitle: 'Deine Erfolge',
  albumTotal: (got: number, total: number) => `${got} von ${total} Erfolgen`,
  albumNew: 'NEU!',
  albumSecretName: '???',
  albumClaim: 'Abholen!',
  albumClaimed: 'Abgeholt',
  albumRewardLocked: 'Sammle alle Erfolge dieser Seite!',
  albumRewardCores: (n: number) => `Belohnung: ⬡ ${n} Kerne`,
  albumRewardColorway: (name: string) => `Belohnung: Farbe „${name}"`,
  albumGoldReward: (n: number) => `Alle ${n} Erfolge: GOLD-Farbe für alle Helden!`,
  albumSince: (date: string) => `Seit ${date}`,
  albumProgress: (got: number, total: number) => `${got}/${total}`,
  newSticker: 'Neuer Erfolg!',
  gameOverNewStickers: 'Neue Erfolge:',
  colorLabel: 'Farbe',
  colorDefault: 'Standard',

  albumPages: {
    start: 'Erste Schritte',
    kampf: 'Kampfkunst',
    bosse: 'Boss-Jäger',
    sammler: 'Sammler',
    meister: 'Meisterschaft',
    team: 'Team-Werk',
    geheim: 'Geheimnisse',
    ausdauer: 'Ausdauer',
    herausforderung: 'Herausforderung',
    geheim2: 'Geheimnisse II',
  } as Record<string, string>,

  colorways: {
    limette: 'Limette',
    aurora: 'Aurora',
    bonbon: 'Bonbon',
    ultraviolett: 'Ultraviolett',
    sonnenglut: 'Sonnenglut',
    tiefsee: 'Tiefsee',
    gold: 'Gold',
    eisblau: 'Eisblau',
    smaragd: 'Smaragd',
    kobalt: 'Kobalt',
    platin: 'Platin',
    prismatisch: 'Prismatisch',
  } as Record<string, string>,

  stickers: {
    ersterFunke: { name: 'Erster Funke', desc: 'Besiege deinen ersten Gegner' },
    wellenreiter: { name: 'Wellenreiter', desc: 'Schaffe deine erste Welle' },
    wusch: { name: 'Wusch!', desc: 'Mache deinen ersten Dash' },
    herzenssache: { name: 'Herzenssache', desc: 'Sammle ein Herz ein' },
    magnetisch: { name: 'Magnetisch', desc: 'Sammle einen Magneten ein' },
    aufgeruestet: { name: 'Aufgerüstet', desc: 'Wähle dein erstes Upgrade' },
    kernSammler: { name: 'Kern-Sammler', desc: 'Sammle insgesamt 100 Kerne' },
    bossInSicht: { name: 'Boss in Sicht', desc: 'Triff auf deinen ersten Boss' },
    blitzblank: { name: 'Blitzblank', desc: 'Schaffe eine Welle ohne Treffer' },
    stammgast: { name: 'Stammgast', desc: 'Spiele 10 Runden' },

    comboKueken: { name: 'Combo-Küken', desc: 'Erreiche Combo ×1,5' },
    comboProfi: { name: 'Combo-Profi', desc: 'Erreiche Combo ×2' },
    comboMeister: { name: 'Combo-Meister', desc: 'Erreiche Combo ×3' },
    scharfschuetze: { name: 'Scharfschütze', desc: 'Lande insgesamt 100 Volltreffer' },
    panzerknacker: { name: 'Panzerknacker', desc: 'Besiege insgesamt 10 Panzer' },
    geisterjaeger: { name: 'Geisterjäger', desc: 'Besiege insgesamt 15 Phantome' },
    eliteSchreck: { name: 'Elite-Schreck', desc: 'Besiege insgesamt 10 Eliten' },
    unberuehrbar: { name: 'Unberührbar', desc: '3 perfekte Wellen in einer Runde' },

    prismaZerlegt: { name: 'Prisma zerlegt', desc: 'Besiege PRISMA' },
    goliathGestuerzt: { name: 'Goliath gestürzt', desc: 'Besiege GOLIATH' },
    minosEntschaerft: { name: 'Minos entschärft', desc: 'Besiege MINOS' },
    hydraGestutzt: { name: 'Hydra gestutzt', desc: 'Besiege den HYDRA-KERN' },
    wirbelGestoppt: { name: 'Wirbel gestoppt', desc: 'Besiege WIRBEL' },
    bossSammlung: { name: 'Boss-Sammlung', desc: 'Besiege alle 5 Bosse' },
    makelloserBoss: { name: 'Makelloser Bosskampf', desc: 'Besiege einen Boss, ohne getroffen zu werden' },
    ueberBoss: { name: 'Über-Boss', desc: 'Besiege einen „+"-Boss (ab Welle 30)' },

    kernschatz: { name: 'Kern-Schatz', desc: 'Sammle insgesamt 500 Kerne' },
    kernDrache: { name: 'Kern-Drache', desc: 'Sammle insgesamt 5.000 Kerne' },
    goldrausch: { name: 'Goldrausch', desc: 'Erlebe eine Goldene Welle' },
    paeckchen: { name: 'Päckchen!', desc: 'Öffne eine Versorgungskapsel' },
    paketProfi: { name: 'Paket-Profi', desc: 'Erhalte alle 4 Kapsel-Belohnungen' },
    tagesheld: { name: 'Tagesheld', desc: 'Beende eine Tages-Arena-Runde' },
    heldenTrio: { name: 'Helden-Trio', desc: 'Beende eine Runde mit jedem Helden' },
    waffenkammer: { name: 'Waffenkammer', desc: 'Beende eine Runde mit jeder Waffe' },
    legendenAlbum: { name: 'Legenden-Album', desc: 'Wähle jedes legendäre Upgrade einmal' },

    welle10: { name: 'Welle 10', desc: 'Erreiche Welle 10' },
    welle15: { name: 'Welle 15', desc: 'Erreiche Welle 15' },
    welle20: { name: 'Welle 20', desc: 'Erreiche Welle 20' },
    harteSchale: { name: 'Harte Schale', desc: 'Erreiche Welle 10 auf Schwer' },
    punkteSturm: { name: 'Punkte-Sturm', desc: '25.000 Punkte in einer Runde' },
    schlaechter1: { name: 'Schlächter I', desc: 'Besiege insgesamt 1.000 Gegner' },
    schlaechter2: { name: 'Schlächter II', desc: 'Besiege insgesamt 5.000 Gegner' },
    schlaechter3: { name: 'Schlächter III', desc: 'Besiege insgesamt 20.000 Gegner' },
    perfektionist: { name: 'Perfektionist', desc: '100 perfekte Wellen insgesamt' },

    doppeltHaelt: { name: 'Doppelt hält besser', desc: 'Beende eine Runde zu zweit' },
    retterInDerNot: { name: 'Retter in der Not', desc: 'Belebe deinen Partner wieder' },
    teamWelle10: { name: 'Team-Welle 10', desc: 'Erreicht zu zweit Welle 10' },
    niemandFaellt: { name: 'Niemand fällt', desc: 'Besiegt einen Boss, ohne dass jemand zu Boden geht' },

    aufFrischerTat: { name: 'Auf frischer Tat', desc: 'Erwische den Dieb, bevor er etwas klaut', hint: 'Schnapp den Langfinger, bevor er zulangt …' },
    spaghettiMonster: { name: 'Spaghetti-Monster', desc: '3 Gegner mit einem Schwarzen Loch verschlingen', hint: 'Füttere die Dunkelheit richtig satt …' },
    standhaft: { name: 'Standhaft', desc: 'Besiege einen Boss ohne einen einzigen Dash', hint: 'Wer nicht springt, gewinnt trotzdem …' },
    umHaaresbreite: { name: 'Um Haaresbreite', desc: 'Beende eine Welle mit höchstens 5 Leben', hint: 'Puh, das war knapp …' },
    wiederDa: { name: 'Wieder da!', desc: 'Nutze die Zweite Chance', hint: 'Es gibt einen Weg zurück … (Psst: Werkstatt!)' },
    goldenePerfektion: { name: 'Goldene Perfektion', desc: 'Schaffe eine Goldene Welle ohne Treffer', hint: 'Wenn alles golden glänzt, bleib makellos …' },

    welle25: { name: 'Welle 25', desc: 'Erreiche Welle 25' },
    welle30: { name: 'Welle 30', desc: 'Erreiche Welle 30' },
    welle35: { name: 'Welle 35', desc: 'Erreiche Welle 35' },
    welle40: { name: 'Welle 40', desc: 'Erreiche Welle 40 — bringt 300 Kerne' },
    welle50: { name: 'Welle 50', desc: 'Erreiche Welle 50 — schaltet die Farbe „Platin" frei' },
    kernMagnat: { name: 'Kern-Magnat', desc: 'Sammle insgesamt 25.000 Kerne' },
    dauerlaeufer: { name: 'Dauerläufer', desc: 'Schaffe insgesamt 300 Wellen' },
    marathon: { name: 'Marathon', desc: 'Schaffe insgesamt 1.000 Wellen — bringt 300 Kerne' },
    veteran: { name: 'Veteran', desc: 'Spiele 50 Runden' },
    altgedienter: { name: 'Altgedienter', desc: 'Spiele 200 Runden' },
    schlaechter4: { name: 'Schlächter IV', desc: 'Besiege insgesamt 50.000 Gegner — bringt 500 Kerne' },

    makelloserKrieger: { name: 'Makelloser Krieger', desc: 'Besiege einen Boss ohne Treffer UND ohne einen Dash' },
    eisenwille: { name: 'Eiserner Wille', desc: 'Erreiche Welle 15, ohne in der ganzen Runde zu dashen' },
    unantastbar: { name: 'Unantastbar', desc: 'Erreiche Welle 10, ohne ein einziges Mal getroffen zu werden — bringt 500 Kerne' },
    hochBoss: { name: 'Gipfelstürmer', desc: 'Besiege einen Boss auf Welle 40 oder höher' },
    fuenfPerfekt: { name: 'Fünf Makellose', desc: 'Schaffe 5 perfekte Wellen in einer Runde' },
    comboKoenig: { name: 'Combo-König', desc: 'Erreiche Combo ×4' },
    comboGott: { name: 'Combo-Gott', desc: 'Erreiche Combo ×5' },
    punkteGott: { name: 'Punkte-Gott', desc: '100.000 Punkte in einer Runde' },
    hartGesotten: { name: 'Hartgesotten', desc: 'Erreiche Welle 20 auf Schwer' },
    titan: { name: 'Titanentöter', desc: 'Besiege insgesamt 100 Panzer' },
    bezwinger: { name: 'Bezwinger', desc: 'Besiege jeden der 5 Bosse mindestens einmal ohne Treffer — schaltet die Regenbogen-Farbe „Prismatisch" frei' },

    paketMeister: { name: 'Paket-Meister', desc: 'Erhalte alle 4 Kapsel-Belohnungen in EINER Runde', hint: 'Sammle in einem Lauf jede Sorte Geschenk …' },
    langfingerJagd: { name: 'Langfinger-Jagd', desc: 'Erwische 10 Diebe, bevor sie klauen', hint: 'Mach Jagd auf die flinken Finger …' },
    schattentaenzer: { name: 'Schattentänzer', desc: 'Besiege einen Boss auf Welle 30+ ohne einen Dash', hint: 'Bleib ruhig stehen, auch wenn es spät wird …' },
    phoenix: { name: 'Phönix', desc: 'Belebe deinen Partner 3-mal in einer Runde wieder', hint: 'Zu zweit gibt niemand auf …' },
    nadeloehr: { name: 'Nadelöhr', desc: 'Beende eine Welle mit höchstens 3 Leben', hint: 'Noch knapper geht kaum …' },
    lochfuerst: { name: 'Loch-Fürst', desc: '5 Gegner mit einem einzigen Schwarzen Loch verschlingen', hint: 'Füttere die Dunkelheit bis zum Rand …' },
    eiserneReserve: { name: 'Eiserne Reserve', desc: 'Erreiche Welle 10, ohne ein Herz zu sammeln', hint: 'Wer clever ausweicht, braucht keine Heilung …' },
    genuegsam: { name: 'Genügsam', desc: 'Erreiche Welle 10, ohne einen Kern aufzusammeln', hint: 'Lass allen Glanz einfach liegen …' },
  } as Record<string, { name: string; desc: string; hint?: string }>,

  // Shop
  shopTitle: 'Werkstatt',
  heroesSection: 'Helden',
  boniSection: 'Dauerhafte Boni',
  weaponsSection: 'Startwaffen',
  buy: 'Kaufen',
  bought: 'Gekauft',
  selected: 'Ausgewählt',
  select: 'Auswählen',
  maxed: 'Maximum',
  back: 'Zurück',
  cores: 'Kerne',

  // Helden
  heroes: {
    volt: { name: 'VOLT', trait: 'Der Allrounder – ausgewogen und zuverlässig' },
    blitz: { name: 'BLITZ', trait: 'Schnell und wendig, aber zerbrechlich' },
    brocken: { name: 'BROCKEN', trait: 'Zäher Koloss mit Streuschuss' },
  } as Record<string, { name: string; trait: string }>,

  // Waffen
  weapons: {
    blaster: { name: 'Neon-Blaster', desc: 'Der treue Standard' },
    pulse: { name: 'Impulskanone', desc: 'Schnellfeuer, wenig Wumms' },
    spread: { name: 'Streuschuss', desc: '3 Kugeln im Fächer' },
    laser: { name: 'Laser-Lanze', desc: 'Durchbohrt ALLES in einer Linie' },
    star: { name: 'Sternenwerfer', desc: 'Bumerang-Stern, trifft doppelt' },
  } as Record<string, { name: string; desc: string }>,

  // Bosse
  bosses: {
    prisma: 'PRISMA',
    goliath: 'GOLIATH',
    minos: 'MINOS',
    hydra: 'HYDRA-KERN',
    vortex: 'WIRBEL',
  } as Record<string, string>,
  bossTierSuffix: '+',

  // Upgrades
  upgrades: {
    fireRate: { name: 'Feuerrate', desc: '+12 % schneller schießen' },
    damage: { name: 'Schaden', desc: '+15 % Schaden' },
    speed: { name: 'Tempo', desc: '+8 % Lauftempo' },
    maxHp: { name: 'Panzerglas', desc: '+20 Leben, die Hälfte sofort geheilt' },
    magnet: { name: 'Magnet', desc: 'Sammelt Kerne von viel weiter weg' },
    range: { name: 'Fernblick', desc: '+20 % Reichweite und Schussgeschwindigkeit' },
    coreGreed: { name: 'Kern-Gier', desc: '+25 % Chance auf Kern-Drops' },
    multishot: { name: 'Mehrfachschuss', desc: '+1 Projektil (etwas weniger Schaden je Kugel)' },
    pierce: { name: 'Durchschlag', desc: 'Kugeln durchbohren +1 Gegner' },
    crit: { name: 'Volltreffer', desc: '+10 % Chance auf doppelten Schaden' },
    lifesteal: { name: 'Lebensraub', desc: '+1 Leben pro 2 Abschüsse' },
    orb: { name: 'Schutz-Orb', desc: 'Kreisender Orb schadet Gegnern' },
    dashBlade: { name: 'Dash-Klinge', desc: 'Dash verletzt durchquerte Gegner' },
    frost: { name: 'Frost-Schuss', desc: 'Treffer verlangsamen Gegner' },
    nova: { name: 'Nova-Kill', desc: '20 % Chance: Explosion bei Abschuss' },
    doubleDash: { name: 'Doppel-Dash', desc: 'Eine zweite Dash-Ladung' },
    ricochet: { name: 'Abpraller', desc: 'Kugeln springen zum nächsten Gegner' },
    mirrorClone: { name: 'Spiegelklon', desc: 'Ein Geisterklon feuert jeden Schuss mit!' },
    chainReaction: { name: 'Kettenreaktion', desc: 'JEDER besiegte Gegner explodiert!' },
    orbitalLaser: { name: 'Orbital-Laser', desc: 'Alle 5 Sekunden: Laser auf den stärksten Gegner' },
    blackHoleDash: { name: 'Schwarzes Loch', desc: 'Dash schleudert ein Schwarzes Loch, das Gegner ansaugt. Dann: Wumms!' },
    overcharge: { name: 'Überladung', desc: 'Unter 30 % Leben: +50 % Schaden' },
    megaShots: { name: 'Mega-Kugeln', desc: 'Riesige Kugeln: mehr Schaden, durchbohren Gegner' },
    // NEU: Mythische Upgrades (ueber legendaer, extrem selten)
    timeBreak: { name: 'Zeitbruch', desc: 'Alle Gegner UND ihre Schüsse stark verlangsamt!' },
    phoenixCore: { name: 'Phönixkern', desc: 'Einmal pro Lauf: Wiederauferstehung mit voller Energie und Schockwelle!' },
    prismBeam: { name: 'Prisma-Strahl', desc: 'Dein Schuss wird zu einem Dauer-Regenbogenstrahl, der alles durchschneidet!' },
    singularity: { name: 'Singularität', desc: 'Feuerrate UND Schaden verdoppelt!' },
    corePack: { name: 'Kern-Paket', desc: 'Sofort +15 Kerne' },
    repair: { name: 'Reparatur', desc: 'Heilt sofort 25 % Leben' },
    scoreBoost: { name: 'Punkte-Schub', desc: 'Sofort Bonuspunkte (500 × Welle)' },
  } as Record<string, { name: string; desc: string }>,

  // Dauerhafte Boni
  permaBoni: {
    armor: { name: 'Panzerung', desc: '+10 % Start-Leben je Stufe' },
    calibration: { name: 'Kalibrierung', desc: '+6 % Schaden je Stufe' },
    turbo: { name: 'Turbo', desc: '+5 % Tempo je Stufe' },
    luck: { name: 'Glückskern', desc: '+10 % Kern-Chance je Stufe' },
    headstart: { name: 'Kopfstart', desc: 'Starte jede Runde mit 1 Gratis-Upgrade' },
    secondChance: { name: 'Zweite Chance', desc: '1× pro Runde: Wiederbelebung mit 50 % Leben' },
  } as Record<string, { name: string; desc: string }>,

  // Onboarding
  promptMove: 'Laufen!',
  promptShoot: 'Schießen!',
  promptDash: 'Dash!',
  promptCollect: 'Kerne einsammeln!',

  // Sonstiges
  clickToStart: 'Klicke, um zu starten',
  revived: 'Zweite Chance!',
  phoenixRevived: '🔥 PHÖNIX! 🔥', // NEU (mythisch "Phoenixkern"): Auferstehungs-Banner
} as const;
